#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'http://localhost:3000/metrics'
polling_headers: 'Content-Type=application/json'
name: Beszel System Metrics
refresh_interval: 60
description: 'Display system metrics from Beszel monitoring via PocketBase'
author: 'TRMNL Community'
category: 'Infrastructure'